name: 'Set Environment'
description: 'Merge globals and environment secrets in one .env file'
inputs:
  globals:
    description: 'The globals secrets'
    required: true
  environment:
    description: 'The environment secrets'
    required: true
branding:
  icon: 'save'
  color: 'yellow'
runs:
  using: 'node16'
  main: 'index.js'
