name: 'Growrk Monorepo'
description: 'Handle the growrk install, build and deploy for monorepo'
inputs:
  is-install:
    description: 'If the action is install'
    required: false
  globals:
    description: 'The globals secrets (install only)'
    required: false
  environment:
    description: 'The environment secrets (install only)'
    required: false
  is-build:
    description: 'If the action is build (name of the package)'
    required: false
  is-deploy:
    description: 'If the action is deploy (name of the package)'
    required: false
branding:
  icon: 'save'
  color: 'yellow'
runs:
  using: 'node16'
  main: 'index.js'
